# Generated by Django 4.1.5 on 2023-04-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inactive_days',
            field=models.IntegerField(default=0),
        ),
    ]
